name: 'Automatic build'
on:
  push:
    branches:
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  continuous-delivery:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Build Site
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll b -d "_site$BASE_URL"

      - name: Deploy
        run: |
          if [[ -n $BASE_URL ]]; then
            mv _site$BASE_URL _site-rename
            rm -rf _site
            mv _site-rename _site
          fi

          bash tools/deploy.sh
